[package]
name = "programming-languages-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
color-eyre = "0.6.2"
crossterm = "0.27.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
rand = "0.8.5"
ratatui = "0.24.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = { version = "0.28.0", features = ["bundled-sqlcipher"] } # SQLite database
tui-big-text = "0.2.1"

